package pl.feature.toggle.service.web;

public enum ErrorCode {
    FEATURE_TOGGLE_NOT_FOUND,
    FEATURE_TOGGLE_ALREADY_EXISTS,
    FEATURE_TOGGLE_WAS_MODIFIED_BY_ANOTHER_REQUEST,
    FEATURE_TOGGLE_ARCHIVED_OPERATION_NOT_ALLOWED,
    ENVIRONMENT_NOT_FOUND,
    ENVIRONMENT_WAS_MODIFIED_BY_ANOTHER_REQUEST,
    ENVIRONMENT_NOT_ASSIGNED_TO_PROJECT,
    ENVIRONMENT_ALREADY_EXISTS,
    ENVIRONMENT_ARCHIVED,
    PROJECT_NOT_FOUND,
    PROJECT_ARCHIVED,
    PROJECT_WAS_MODIFIED_BY_ANOTHER_REQUEST,
    PROJECT_ALREADY_EXISTS,
    ERROR,
    VALIDATION_ERROR,
}
